spring.application.name=prometheus-example

# Expose key actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus,env,threaddump,heapdump
management.endpoint.health.show-details=always

# (optional) rename base path if you want it under /api/actuator instead of /actuator
management.endpoints.web.base-path=/actuator

# Prometheus endpoint
management.metrics.export.prometheus.enabled=true



