spring.application.name=prometheus-example

# Expose key actuator endpoints
#management.endpoints.web.exposure.include=health,info,metrics,prometheus,env,threaddump,heapdump
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

# (optional) rename base path if you want it under /api/actuator instead of /actuator
management.endpoints.web.base-path=/actuator

management.endpoint.prometheus.enabled=true

# Prometheus endpoint
management.metrics.export.prometheus.enabled=true

# Truststore settings
oauth.custom.baseUrl=http://localhost:8080/oauth2
oauth.custom.clientId=prometheus-client
oauth.custom.clientSecret=prometheus-secret
oauth.custom.scopes=read_metrics
oauth.custom.realmPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV7q4c6v6u2c1+gk5g5h3FJ1bXGZV3Y2jUO5vW8sXjF5x6tH3FQKBgQDqX9Jv+8wIDAQAB
oauth.custom.realmPublicKeyAlgorithm=RSA
oauth.custom.realmPublicKeyUrl=http://localhost:8080/oauth2/realms/publickey
oauth.custom.trust-store-path=classpath:keystore.p12
oauth.custom.trust-store-password=changeit
oauth.custom.trust-store-type=PKCS12





